set-option -g history-limit 25000
set -g mouse on

# Set leader to Ctrl+space
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# for neovim
set -sg escape-time 10
# Enables copy/paste in neovim over ssh
set -g set-clipboard on


# key bindings for swapping windows
bind-key C-h swap-window -t -1\; select-window -t -1
bind-key C-l swap-window -t +1\; select-window -t +1
bind-key C-m command-prompt -p "Move window to index:" "move-window -b -t %%"

# key bindings for resizing panes
bind-key -r h resize-pane -L 5
bind-key -r j resize-pane -D 5
bind-key -r k resize-pane -U 5
bind-key -r l resize-pane -R 5

# clear history
bind-key C-k send-keys -R ^M \; clear-history

# count the panes from 1
set -g base-index 1
setw -g pane-base-index 1

# renumber windows when window is closed
set -g renumber-windows on

# overrides for split
bind-key v split-window -v -c "#{pane_current_path}"
bind-key s split-window -h -c "#{pane_current_path}"

# rename window
bind-key r command-prompt "rename-window %%"

# fzf session switcher (enter=switch, ctrl-r=rename)
bind-key f display-popup -E "~/.config/tmux/session-switcher.sh"

# reload configuration
bind-key R source-file ~/.config/tmux/tmux.conf

# term colors, these are the correct ones according to neovim checkhealth
set-option -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

# Styling
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session
set -g @dracula-plugins "none"
set -g status-position top

set -g update-environment "SSH_AUTH_SOCK"
setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock

# Navigate between vim and tmux
set -g @plugin 'christoomey/vim-tmux-navigator'

# Persist sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Better yanking
set -g @plugin 'tmux-plugins/tmux-yank'
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# If TPM is not installed, install it and install plugins
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
